<?php View::content(); ?>
<link href="<?php echo PUBLIC_PATH ?>css/plugins/dataTables.bootstrap.css"  rel="stylesheet" type="text/css">

<!-- Lista de usuarios -->
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="box box-success" >
      <div class="box-header">
        <h3 class="text-navy">Ver todos los usuarios</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-lg-12 col-md-12 small">
            <table class="table table-hover table-striped table-condensed" id="tabla_usuarios">
              <thead>
                <th>login</th>
                <th>Nombre</th>
                <th>activo</th>
                <th>subprocuraduria</th>
                <th>Niveles</th>
                <th>Resetear clave</th>
                <th>Editar</th>
              </thead>
              <tbody>
                <?php foreach ($usuarios as $key): ?>
                  <tr>
                    <td><?php echo utf8_encode($key->login) ?></td>
                    <td><?php echo ($key->getNombre())   ?></td>
                    <td><?php echo $key->activo ?></td>
                    <td><?php echo $key->subprocuradurias_id?($key->getSubprocuradurias()->subprocuraduria):'No registrado'?></td>
                    <td><?php echo $key->getNiveles()->nivel ?></td>
                    <td><a href="<?php echo PUBLIC_PATH.'usuarios/resetear/'.Cifrar::todo($key->id)?>"><i class="fa fa-eraser text-red"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'usuarios/editar/'.Cifrar::todo($key->id)?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                  </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--FIN: Lista de usuarios -->

<?php echo Form::open("usuarios/crear",'POST','class="form form-horizontal"'); ?>

    <div class="box box-primary">
      <div class="box-header"><h3>Registro de nuevo usuario</h3></div>
      <div class="box-body">
       
              <div class="col-md-3">
                        <label class="control-label">Titulo</label>
                        <input type="text" name="usuarios[titulo]" id="usuarios_titulo" value="<?php echo @$_POST['usuarios']['titulo'] ?>" class="form-control mayuscula"  > 
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nombre Real</label>
                        <input type="text" name="usuarios[nombre]"value="<?php echo @$_POST['usuarios']['nombre'] ?>" class="form-control mayuscula" required="" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">A. Paterno:</label>
                        <input type="text" name="usuarios[paterno]" value="<?php echo @$_POST['usuarios']['paterno'] ?>" class="form-control mayuscula" required="" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">A. Materno:</label>
                        <input type="text" name="usuarios[materno]" value="<?php echo @$_POST['usuarios']['materno'] ?>" class="form-control mayuscula">
                    </div>



                    <div class="col-md-3 ">
                        <label class="control-label">Jefe:</label>

                        <?php echo Form::dbSelect('usuarios.jefe', 'nombre', array('usuarios', 'listar'), 'SELECCIONE', 'class="form-control" required'); ?>

                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nombre de usuario:</label>
                        <input type="text" name="login" value="<?php echo @$_POST['usuarios']['login'] ?>" id="usuarios_login" class="form-control" placeholder="Usuario" ddata-remote="<?php echo PUBLIC_PATH ?>usuarios/getExistente" delay="10" required="">
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Password:</label>
                        <input type="password" name="usuarios[clave]" id="clave" data-minlength="5" class="form-control" ="" data-error="Minimo 5 caracteres" required="">
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Repetir Password:</label>
                        <input type="password" name="usuarios[repite]" class="form-control"    data-match="#clave" data-match-error="Ups! No coinciden las contraseñas" required="" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Activo:</label>
                        <select name="usuarios[activo]" class="form-control">
                            <option value="S">Si</option>
                            <option value="N" >No</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nivel:</label>
                        <?php echo Form::dbSelect('usuarios.niveles_id', 'nivel', array('niveles', 'listar'), 'SELECCIONE', 'class="form-control" required '); ?>
                    </div>

                     <div class="col-md-3 ">
                        <label>Area</label>
                        <?php echo Form::dbSelect('usuarios.areas_id', 'area', array('areas', 'find'), 'Seleccione', ' class="form-control" data-live-search="true"required ') ?>
                    </div>


                    <div class="col-md-3">
                        <label class="control-label">Captura:</label>
                        <select name="usuarios[captura]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->reportes == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->reportes == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Consultas:</label>
                        <select name="usuarios[consultas]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->consultas == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->consultas == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Reportes:</label>
                        <select name="usuarios[reportes]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->Reportes == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->Reportes == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Todas:</label>
                        <select name="usuarios[todas]" class="form-control" >
                            <option value="S" <?php echo isset($usuario) ? ($usuario->todas == 'S' ? 'selected' : '') : '' ?>>SI</option>
                            <option value="N" <?php echo isset($usuario) ? ($usuario->todas == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                   
                    <div class="col-md-3">
                        <label class="control-label">Subprocuraduria:</label>
                        <?php echo Form::dbSelect('usuarios.subprocuradurias_id', 'subprocuraduria', array('subprocuradurias', 'find'), 'SELECCIONE', 'class="form-control" required'); ?>
                    </div>
               



</div>

      <div class="box-footer">
        <div class="col-lg-3 col-md-3 pull-right">
          <button type="reset" class="btn btn-warning btn-flat" style="margin-right:10px;">Limpiar</button>
          <button type="submit" name="formulario" class="btn btn-success btn-flat">Registrar</button>
        </div> 
      </div>
    </div>     
  </div>
</div>

<?php echo Form::close(); ?>



<!-- Form close -->

<?php echo Tag::js('plugins/datatables/jquery.dataTables.min'); ?>
<?php echo Tag::js('plugins/datatables/dataTables.bootstrap.min'); ?>
<?php echo Tag::js('usuarios/usuarios'); ?>
