<link href="<?php echo PUBLIC_PATH ?>css/select2/select2.min.css" rel="stylesheet" type="text/css" media="screen">
<style type="text/css" media="screen">
  .select2-container--default 
  .select2-selection--multiple 
  .select2-selection__choice{
    background-color: #878787;
  }
</style>
<?php View::content(); ?>

<?php echo Form::open("usuarios/editar/".Cifrar::todo($usuario->id),'POST','class=" form-horizontal"'); ?>
<div class="row">
  <div class="col-lg-12">
    <div class="box box-primary">
      <div class="box-header"><h3>Edición del usuario</h3></div>
         <div class="col-md-3">
                        <label class="control-label">Titulo</label>
                        <input type="text" name="usuarios[titulo]" id="usuarios_titulo" value="<?php echo @$_POST['usuarios']['titulo'] ?>" class="form-control mayuscula" > 
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nombre Real</label>
                        <input type="text" name="usuarios[nombre]"value="<?php echo @$_POST['usuarios']['nombre'] ?>" class="form-control mayuscula" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">A. Paterno:</label>
                        <input type="text" name="usuarios[paterno]" value="<?php echo @$_POST['usuarios']['paterno'] ?>" class="form-control mayuscula" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">A. Materno:</label>
                        <input type="text" name="usuarios[materno]" value="<?php echo @$_POST['usuarios']['materno'] ?>" class="form-control mayuscula">
                    </div>



                    <div class="col-md-3 ">
                        <label class="control-label">Jefe:</label>

                        <?php echo Form::dbSelect('usuarios.jefe', 'nombre', array('usuarios', 'listar'), 'SELECCIONE', 'class="form-control"'); ?>

                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nombre de usuario:</label>
                        <input type="text" name="login" value="<?php echo @$_POST['usuarios']['login'] ?>" id="usuarios_login" class="form-control" placeholder="Usuario" ddata-remote="<?php echo PUBLIC_PATH ?>usuarios/getExistente" delay="10" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Password:</label>
                        <input type="password" name="usuarios[clave]" id="clave" data-minlength="5" class="form-control" ="" data-error="Minimo 5 caracteres">
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Repetir Password:</label>
                        <input type="password" name="usuarios[repite]" class="form-control"    data-match="#clave" data-match-error="Ups! No coinciden las contraseñas" >
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Activo:</label>
                        <select name="usuarios[activo]" class="form-control">
                            <option value="S">Si</option>
                            <option value="N" >No</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Nivel:</label>
                        <?php echo Form::dbSelect('usuarios.niveles_id', 'nivel', array('niveles', 'listar'), 'SELECCIONE', 'class="form-control" '); ?>
                    </div>

                     <div class="col-md-3 ">
                        <label>Area</label>
                        <?php echo Form::dbSelect('usuarios.areas_id', 'area', array('areas', 'find'), 'Seleccione', ' class="form-control" data-live-search="true" ') ?>
                    </div>


                    <div class="col-md-3">
                        <label class="control-label">Captura:</label>
                        <select name="usuarios[captura]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->reportes == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->reportes == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Consultas:</label>
                        <select name="usuarios[consultas]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->consultas == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->consultas == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Reportes:</label>
                        <select name="usuarios[reportes]" class="form-control">
                            <option value="S"<?php echo isset($usuario) ? ($usuario->Reportes == 'S' ? 'selected' : '') : '' ?>>Si</option>
                            <option value="N"<?php echo isset($usuario) ? ($usuario->Reportes == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                    <div class="col-md-3">
                        <label class="control-label">Todas:</label>
                        <select name="usuarios[todas]" class="form-control" >
                            <option value="S" <?php echo isset($usuario) ? ($usuario->todas == 'S' ? 'selected' : '') : '' ?>>SI</option>
                            <option value="N" <?php echo isset($usuario) ? ($usuario->todas == 'N' ? 'selected' : '') : '' ?>>NO</option>
                        </select>
                    </div>

                   
                    <div class="col-md-3">
                        <label class="control-label">Subprocuraduria:</label>
                        <?php echo Form::dbSelect('usuarios.subprocuradurias_id', 'subprocuraduria', array('subprocuradurias', 'find'), 'SELECCIONE', 'class="form-control" '); ?>
                    </div>
               



       <div class="box-footer">
        <div class="col-lg-3 col-md-3 pull-right">
          <button type="reset" class="btn btn-warning btn-flat" style="margin-right:10px;">Limpiar</button>
          <button type="submit" value="formulario" name="formulario" class="btn btn-success btn-flat">Registrar</button>
        </div> 
      </div>
    </div>     
  </div>
</div>
<?php echo Form::close(); ?>



<!-- Form close -->
<?php echo Tag::js('usuarios/usuarios'); ?>
<?php echo Tag::js('plugins/select2/select2.full.min'); ?>
<?php echo Tag::js('plugins/select2/i18n/es'); ?>
